# Generated by Django 6.0 on 2026-03-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='lessons/presentation'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons/video'),
        ),
    ]
