# Generated by Django 6.0 on 2025-12-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, unique=True),
        ),
    ]
