# Generated by Django 6.0 on 2025-12-15 12:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_price', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(choices=[('PAYME', 'payme'), ('CLICK', 'click')], max_length=10)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
